package testutil

import (
	"time"

	"github.com/rclod/codewalk/internal/walkthrough"
)

// SampleWalkthrough returns a structurally complete walkthrough describing the
// fictional orders service in SampleService. It is used wherever a test needs a
// realistic walkthrough without calling a model.
func SampleWalkthrough() *walkthrough.Walkthrough {
	w := &walkthrough.Walkthrough{
		SchemaVersion: walkthrough.SchemaVersion,
		ID:            "test-walkthrough",
		Kind:          walkthrough.KindChange,
		Title:         "Order creation moves to a background worker",
		Headline:      "Order creation now persists the order and finishes the work in a background worker instead of completing during the HTTP request.",
		Summary:       "The API handler writes the order and returns immediately. A worker picks the order up and completes payment authorisation.",
		Scope: walkthrough.Scope{
			RepositoryName: "orders",
			Selector:       "branch",
			Base:           "main",
			Head:           "feature",
			Stats:          walkthrough.ChangeStats{FilesChanged: 3, Insertions: 120, Deletions: 24},
			ChangedFiles: []walkthrough.ChangedFile{
				{Path: "internal/orders/service.go", Status: "modified", Insertions: 20, Deletions: 24},
				{Path: "internal/orders/worker.go", Status: "added", Insertions: 90},
				{Path: "package-lock.json", Status: "modified", Insertions: 10, Generated: true},
			},
		},
		Complexity: walkthrough.Complexity{Level: 4, Label: "architectural", Rationale: "A synchronous path becomes asynchronous."},
		Concepts: []walkthrough.Concept{
			{ID: "async-completion", Name: "Asynchronous completion", Summary: "Work that used to finish inside the request now finishes later.", WhyItMatters: "The response no longer means the order is complete."},
		},
		Components: []walkthrough.Component{
			{ID: "service", Name: "OrderService", Kind: "service", Responsibility: "Creates and persists orders.", Status: walkthrough.StatusChanged, Files: []string{"internal/orders/service.go"}},
			{ID: "worker", Name: "OrderWorker", Kind: "worker", Responsibility: "Completes order processing in the background.", Status: walkthrough.StatusNew, Files: []string{"internal/orders/worker.go"}},
		},
		Relationships: []walkthrough.Relationship{
			{From: "service", To: "worker", Kind: "publishes", Label: "OrderCreated"},
		},
		Flows: []walkthrough.Flow{
			{
				ID: "create", Name: "Create an order", Trigger: "POST /orders",
				Steps: []walkthrough.FlowStep{
					{From: "service", To: "worker", Action: "publish OrderCreated", Async: true},
				},
				Outcome: "The order exists and is processed asynchronously.",
			},
		},
		Steps: []walkthrough.Step{
			{
				ID: "context", Title: "How order creation worked before", Kind: walkthrough.StepBefore,
				Summary:     "Everything happened inside the HTTP request.",
				Explanation: "`OrderService.Create` wrote the order and authorised payment before returning.",
				Components:  []string{"service"},
				CodeRefs: []walkthrough.CodeReference{
					{Path: "internal/orders/service.go", Symbol: "Service.Create", StartLine: 1, EndLine: 5, Side: "before"},
				},
			},
			{
				ID: "worker", Title: "The worker takes over completion", Kind: walkthrough.StepComponent,
				Summary:     "A new worker finishes the work after the response is sent.",
				Explanation: "The handler returns once the order is stored. `OrderWorker` picks it up and authorises payment.",
				Components:  []string{"worker"},
				Diagrams: []walkthrough.Diagram{
					{
						ID: "create-flow", Title: "Order creation", Format: walkthrough.DiagramMermaid,
						Source: "sequenceDiagram\n    Browser->>API: POST /orders\n    API->>OrderService: Create()\n    OrderService->>Worker: OrderCreated",
					},
				},
				DeepDive: &walkthrough.DeepDive{Title: "Retry behaviour", Explanation: "Failed work is retried on the next poll."},
			},
			{
				ID: "outcome", Title: "What a caller sees now", Kind: walkthrough.StepOutcome,
				Summary:     "A successful response means the order was accepted, not completed.",
				Explanation: "Callers receive the order id immediately; completion happens later.",
				CodeRefs: []walkthrough.CodeReference{
					{Path: "internal/orders/service.go", StartLine: 1, EndLine: 3},
				},
			},
		},
		BeforeAfter: &walkthrough.BeforeAfter{
			Summary: "The same work now spans two execution contexts.",
			Aspects: []walkthrough.BeforeAfterItem{
				{Aspect: "When payment is authorised", Before: "During the request.", After: "In the worker, after the response."},
			},
		},
		StartHere: []walkthrough.CodeReference{
			{Path: "internal/orders/service.go", Note: "The entry point for the new flow."},
		},
		Ignorable: []walkthrough.Ignorable{
			{Path: "package-lock.json", Reason: "A dependency lockfile regenerated by the build."},
		},
		Uncertainties: []walkthrough.Uncertainty{
			{Question: "How often does the worker poll?", Known: "The interval is configured outside this repository.", WhereNext: "Deployment configuration."},
		},
		Meta: walkthrough.Meta{GeneratedAt: time.Now().UTC(), Generator: "codewalk/test"},
	}
	w.Normalize()
	return w
}
