package render

import (
	"fmt"
	"io"
	"strings"

	"github.com/rclod/codewalk/internal/walkthrough"
)

// Markdown writes a walkthrough as a Markdown document. Diagrams are emitted as
// Mermaid fences, which render in most Markdown viewers and stay diffable in
// plain text.
func Markdown(out io.Writer, w *walkthrough.Walkthrough) error {
	p := func(format string, args ...any) { fmt.Fprintf(out, format, args...) }

	p("# %s\n\n", w.Title)
	p("%s\n\n", w.Headline)
	if w.Summary != "" {
		p("%s\n\n", w.Summary)
	}
	p("*%s · complexity %d (%s)*\n\n", scopeLine(w), w.Complexity.Level, w.Complexity.Label)

	if len(w.Concepts) > 0 {
		p("## Concepts you need\n\n")
		for _, c := range w.Concepts {
			p("**%s** — %s\n", c.Name, c.Summary)
			if c.WhyItMatters != "" {
				p("  \n%s\n", c.WhyItMatters)
			}
			p("\n")
		}
	}

	if w.Architecture != nil && w.Architecture.Overview != "" {
		p("## Where this sits\n\n%s\n\n", w.Architecture.Overview)
		writeDiagramByID(out, w, w.Architecture.DiagramID)
	}

	if w.BeforeAfter != nil && len(w.BeforeAfter.Aspects) > 0 {
		p("## Before and after\n\n")
		if w.BeforeAfter.Summary != "" {
			p("%s\n\n", w.BeforeAfter.Summary)
		}
		p("| Aspect | Before | After |\n| --- | --- | --- |\n")
		for _, a := range w.BeforeAfter.Aspects {
			p("| %s | %s | %s |\n", escapeCell(a.Aspect), escapeCell(a.Before), escapeCell(a.After))
		}
		p("\n")
	}

	p("## Walkthrough\n\n")
	for i, step := range w.Steps {
		p("### %d. %s\n\n", i+1, step.Title)
		if step.Summary != "" {
			p("*%s*\n\n", step.Summary)
		}
		p("%s\n\n", strings.TrimSpace(step.Explanation))

		for _, d := range step.Diagrams {
			writeDiagram(out, d)
		}
		if len(step.CodeRefs) > 0 {
			p("**Code:**\n\n")
			for _, ref := range step.CodeRefs {
				p("- `%s`", refLabel(ref))
				if ref.Note != "" {
					p(" — %s", ref.Note)
				}
				p("\n")
				if ref.Snippet != "" {
					p("\n```\n%s\n```\n", strings.TrimRight(ref.Snippet, "\n"))
				}
			}
			p("\n")
		}
		if step.DeepDive != nil {
			title := step.DeepDive.Title
			if title == "" {
				title = "Deep dive"
			}
			p("<details>\n<summary>%s</summary>\n\n%s\n\n", title, strings.TrimSpace(step.DeepDive.Explanation))
			for _, d := range step.DeepDive.Diagrams {
				writeDiagram(out, d)
			}
			p("</details>\n\n")
		}
	}

	for _, d := range w.Diagrams {
		if usedInStep(w, d.ID) {
			continue
		}
		writeDiagram(out, d)
	}

	if len(w.StartHere) > 0 {
		p("## Where to start reading\n\n")
		for _, ref := range w.StartHere {
			p("- `%s`", refLabel(ref))
			if ref.Note != "" {
				p(" — %s", ref.Note)
			}
			p("\n")
		}
		p("\n")
	}
	if len(w.Ignorable) > 0 {
		p("## Safe to skip for now\n\n")
		for _, ig := range w.Ignorable {
			label := ig.Path
			if label == "" {
				label = ig.Area
			}
			p("- `%s` — %s\n", label, ig.Reason)
		}
		p("\n")
	}
	if len(w.Glossary) > 0 {
		p("## Glossary\n\n")
		for _, g := range w.Glossary {
			p("- **%s** — %s", g.Term, g.Definition)
			if len(g.UsedHere) > 0 {
				p(" (%s)", strings.Join(g.UsedHere, ", "))
			}
			p("\n")
		}
		p("\n")
	}
	if len(w.Uncertainties) > 0 {
		p("## Not established\n\n")
		for _, u := range w.Uncertainties {
			p("- **%s**", u.Question)
			if u.Known != "" {
				p(" Known: %s", u.Known)
			}
			if u.Unknown != "" {
				p(" Unknown: %s", u.Unknown)
			}
			if u.WhereNext != "" {
				p(" Where to look: %s", u.WhereNext)
			}
			p("\n")
		}
		p("\n")
	}

	p("---\n\n*Generated by %s. This walkthrough explains the code; it is not a code review.*\n",
		orDefault(w.Meta.Generator, "codewalk"))
	return nil
}

func writeDiagram(out io.Writer, d walkthrough.Diagram) {
	if strings.TrimSpace(d.Source) == "" {
		return
	}
	if d.Title != "" {
		fmt.Fprintf(out, "**%s**\n\n", d.Title)
	}
	fmt.Fprintf(out, "```%s\n%s\n```\n\n", d.Format, strings.TrimSpace(d.Source))
	if d.Caption != "" {
		fmt.Fprintf(out, "*%s*\n\n", d.Caption)
	}
}

func writeDiagramByID(out io.Writer, w *walkthrough.Walkthrough, id string) {
	if id == "" {
		return
	}
	for _, d := range w.AllDiagrams() {
		if d.ID == id {
			writeDiagram(out, d)
			return
		}
	}
}

func usedInStep(w *walkthrough.Walkthrough, id string) bool {
	for _, s := range w.Steps {
		for _, d := range s.Diagrams {
			if d.ID == id {
				return true
			}
		}
	}
	if w.Architecture != nil && w.Architecture.DiagramID == id {
		return true
	}
	return false
}

func escapeCell(s string) string {
	s = oneLine(s)
	return strings.ReplaceAll(s, "|", "\\|")
}

func orDefault(v, def string) string {
	if v == "" {
		return def
	}
	return v
}
